name: "Connect With SF Org"
on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch to compare against (e.g., main)'
        required: true
        default: 'master'
jobs:
    validate-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Set dynamic branch variables
              id: vars
              run: |
                echo "##[group]Branch context"
                echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
                echo "BASE_BRANCH=${{ github.event.inputs.base_branch }}"
                echo "##[endgroup]"

                echo "from=${{ github.event.inputs.base_branch }}" >> $GITHUB_OUTPUT
                echo "to=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
              
            - name: Install SF CLI
              run: |
                if [[ $(sf) ]];
                then
                    echo "SF cli is present"
                else
                    echo "Installing sf..."
                    curl https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.gz -o sf-linux-x64.tar.gz
                    mkdir -p sf-cli
                    tar -xzf sf-linux-x64.tar.gz -C sf-cli --strip-components 1
                    echo "${PWD}/sf-cli/bin" >> $GITHUB_PATH
                fi

            - name: Check SF Version
              run: sf --version

            - name: Install Plugins (Delta Plugin)
              run: echo y | sf plugins install sfdx-git-delta

            - name: Get Delta
              run: |
                sfdx sgd:source:delta --to ${{ steps.vars.outputs.to }} --from ${{ steps.vars.outputs.from }} --output-dir .
                ls -la

            - name: Write Auth URL to File
              run: echo "${{ secrets.SF_TRG_SECURITY }}" > dxsecurity

            - name: Authorize the SF Org
              run: |
                sf org login sfdx-url --sfdx-url-file dxsecurity --alias ${{ secrets.SF_TRG_ORG_ALIAS }} --set-default
                echo "Authorized org and set alias to [${{ secrets.SF_TRG_ORG_ALIAS }}]"

            - name: Validate the Delta Package
              run: |
                sf project deploy start --dry-run --manifest package/package.xml --pre-destructive-changes destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --target-org ${{ secrets.SF_TRG_ORG_ALIAS }}