name: "Connect With SF Org"
on: workflow_dispatch
jobs:
    validate-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Code
              uses: actions/checkout@v3
              with:
                fetch-depth: 2
              
            - name: Install SF CLI
              run: |
                if [[ $(sf) ]];
                then
                    echo "SF cli is present"
                else
                    echo "Installing sf..."
                    curl https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.gz -o sf-linux-x64.tar.gz
                    mkdir -p sf-cli
                    tar -xzf sf-linux-x64.tar.gz -C sf-cli --strip-components 1
                    echo "${PWD}/sf-cli/bin" >> $GITHUB_PATH
                fi

            - name: Check SF Version
              run: sf --version

            - name: Install Plugins (Delta Plugin)
              run: echo y | sf plugins install sfdx-git-delta

            - name: Get Delta
              run: |
                sfdx sgd:source:delta --to HEAD --from HEAD^ --output-dir .
                ls -la

            - name: Write Auth URL to File
              run: echo "${{ secrets.SF_TRG_SECURITY }}" > dxsecurity

            - name: Authorize the SF Org
              run: |
                sf org login sfdx-url --sfdx-url-file dxsecurity --alias ${{ secrets.SF_TRG_ORG_ALIAS }} --set-default
                echo "Authorized org and set alias to [${{ secrets.SF_TRG_ORG_ALIAS }}]"

            - name: Validate the Delta Package
              run: |
                # sf project deploy start --manifest package/package.xml --pre-destructive-changes destructiveChanges/destructiveChanges.xml --test-level RunLocalTests --dry-run --target-org ${{ secrets.SF_TRG_ORG_ALIAS }}
                sf project deploy validate --manifest package/package.xml --pre-destructive-changes destructiveChanges/destructiveChanges.xml --target-org ${{ secrets.SF_TRG_ORG_ALIAS }} --verbose --test-level RunLocalTests